In [1]:
import numpy as np

In [2]:
list1 = [10, 20, 30]

In [3]:
list1

[10, 20, 30]

In [4]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
list1 and arr1

array([10, 20, 30])

In [7]:
list1
arr1

array([10, 20, 30])

In [8]:
arr2 = np.arange(10, 20, 1)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
list2 = [40, 50, 60]

# join the two lists together
list3 = [list1, list2]

# create an array out of the joined lists
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [10]:
# two-dimensional array, with 2 elements in the first instance and 3 in the second
arr3.shape

(2, 3)

In [11]:
arr3dim = np.array([[[1, 2, 3], [3, 4, 5,]], [[5, 6, 7], [7, 8, 9]]])
arr3dim

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [12]:
arr3dim.shape

(2, 2, 3)

In [13]:
arr3dim * 3

array([[[ 3,  6,  9],
        [ 9, 12, 15]],

       [[15, 18, 21],
        [21, 24, 27]]])

In [14]:
list1 * 3

[10, 20, 30, 10, 20, 30, 10, 20, 30]

In [15]:
arr11 = np.array(list2)

# individual numbers will be multiplied based on their positions
arr1 * arr11

array([ 400, 1000, 1800])

In [16]:
# not possible to multiply arrays of different shapes
arr1 * arr2

ValueError: operands could not be broadcast together with shapes (3,) (10,) 

In [18]:
# but it is possible to multiply together arrays with different dimensions, but the same element size
arr1 * arr3dim

array([[[ 10,  40,  90],
        [ 30,  80, 150]],

       [[ 50, 120, 210],
        [ 70, 160, 270]]])

In [22]:
# LAB
arr1dim = np.arange(1, 13, 1)
arr1dim

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
arr1dim.shape

(12,)

In [25]:
arr2dim = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr2dim

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
arr2dim.shape

(3, 4)

In [30]:
arr3dim = np.array([[[1, 1, 1, 1], [2, 2, 2, 2], [1, 1, 1, 1], [2, 2, 2, 2], [1, 1, 1, 1]], [[3, 3, 3, 3], [4, 4, 4, 4], [3, 3, 3, 3], [4, 4, 4, 4], [3, 3, 3, 3]]])
arr3dim

array([[[1, 1, 1, 1],
        [2, 2, 2, 2],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [1, 1, 1, 1]],

       [[3, 3, 3, 3],
        [4, 4, 4, 4],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [3, 3, 3, 3]]])

In [31]:
arr3dim.shape

(2, 5, 4)

In [32]:
# How can we access the 60?
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [33]:
# indexing starts at 0 and we will access each piece of the ndarray in order
arr3[1, 2]

60

In [34]:
# for the bottom row index at 1
arr3[1]

array([40, 50, 60])

In [35]:
# It's east to access each row, and specific values like this but what if we wanted just the last column?
# : means everything, so essentially we are selecting everything, and then just position 2 of the result
arr3[:,2]

array([30, 60])

In [36]:
arr3.sum()

210

In [37]:
# the sum of the values column-wise
arr3.sum(0)

array([50, 70, 90])

In [38]:
# sum of the values row-wise
arr3.sum(1)

array([ 60, 150])

In [39]:
arr3.mean()

35.0

In [41]:
arr3.std()

17.07825127659933

In [42]:
arr3.var()

291.6666666666667

In [43]:
arr3.min()

10

In [44]:
arr3.max()

60

In [46]:
# iterating through a one-dimensional array
for x in arr1:
    print(x)

10
20
30


In [48]:
# iterating through an n-dimensional array, we need to iterate through each dimension until we get the value
for dim in arr3:
    for num in dim:
        print(num)

10
20
30
40
50
60


In [49]:
# Alternatively - we can use nditer
# This can be used from very basic to very complex iterations
# It will be much neater than nested for loops
for x in np.nditer(arr3):
    print(x)

10
20
30
40
50
60


In [50]:
# to save an array as a file
np.save("new", arr3)

In [51]:
# loading the file
np.load("new.npy")

array([[10, 20, 30],
       [40, 50, 60]])

In [52]:
# saving as txt
np.savetxt("new.txt", arr3, delimiter = ',')

In [53]:
# loading a txt
np.loadtxt("new.txt", delimiter = ',')

array([[10., 20., 30.],
       [40., 50., 60.]])